# list of paths to directories that should be crawled
paths: [/home/menko/Documents/Bloxico/filecoin/system-test-matrix/test-crawler/_modules/lotus]
# stdout or file(json)
output: file
# if output is file, choose directory
output_dir: outputs
# auto or one of the supported languages for specific repo
lang_mode: go
# should the output JSON be indented
indent_json: true
# ignore paths
ignore: ["extern"]