#
# This workflow will auto merge dependabot PRs with minor version update.
#

name: auto-merge

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/package.json'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout the repository.
      #
      - uses: actions/checkout@v2

      #
      # Merge minor versions
      #
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
