name: Deploy Test Crawler

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - test-crawler/**
on:
  repository_dispatch:
    types: [testing-repository-dispatch]

jobs:
  run-test-crawler:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository.
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Move uniqueREADME because it gets deleted when cloning repo
      - name: Move readme file
        run: mv repo-to-crawl/uniqueREADME.md ./

      # Clone lotus repo into repo-to-crawl folder
      - name: Clone lotus  repo
        uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          path: repo-to-crawl

      # Install go lang
      - name: Install go lang 1.17.7
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.7"

      # Run test crawler
      - name: Make run
        run: make run
        working-directory: test-crawler

      # Copy crawler output
      - name: Copy output
        run: make copy-output
        working-directory: test-crawler

      # Delete cloned repo
      - name: Delete cloned repo
        run: find . -delete
        working-directory: repo-to-crawl

      # Move back uniqueREADME
      - name: Move readme file back
        run: mv uniqueREADME.md repo-to-crawl

      # Create Pull Request for this action
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: chore/generate-tests
          commit-message: Update tests.json
          title: "chore(test-crawler): Update tests.json"
          delete-branch: true
